project:
  type: website

website: 
  title: "Sadraque Lucena"
  navbar:
    pinned: true
    left:
      - href: topbar/sobremim.qmd
        text: "Sobre mim"
      - href: topbar/disciplinas.qmd
        text: "Disciplinas ministradas"
      - href: topbar/publicacoes.qmd
        text: "Publicações"
    
    tools:
      - href: https://github.com
        icon: github

format:
  html:
    page-layout: full # the page content takes up more of the page width